[package]
name = "karpender"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { package = "libadwaita", version = "0.8" }
anyhow = "1"
atomic_float = "1"
gtk = { package = "gtk4", version = "0.10" }
pipewire = { version = "0.10", features = ["v1_2_0"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spa = { package = "libspa", version = "0.10", features = ["v1_6_0"] }

[patch.crates-io]
libspa = { path = "vendor/libspa-0.10.0" }
pipewire = { path = "vendor/pipewire-0.10.0" }
